spring.application.name=CustomerServiceAI

spring.mail.host=telebit.sk
spring.mail.port=25
spring.mail.username=tomasmravec@telebit.sk
spring.mail.password=Dur3d285_8/

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false

ghl.base-url=https://services.leadconnectorhq.com
ghl.api-version=2021-04-15
ghl.token=
app.recordings-dir=recordings

openai.api-key=
openai.transcription.model=gpt-4o-transcribe
openai.transcription.language=sk
